version: "3.7"

networks:
  app-net: null

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: michikite/dev-container-conda
    networks:
      - app-net
    volumes:
      - ../:/workspace
