version: "3.8"

services:
  dev-app:
    build: .
    links:
      - "relational-db:relational-db"
    ports:
      - 3001:3001
    volumes:
      - .:/app
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=relational-db user=postgres password=not_so_secret dbname=postgres sslmode=disable
    profiles:
      - dev
    command: sleep infinity

  relational-db:
    image: postgres:16
    restart: always
    logging:
      driver: none
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: not_so_secret
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    volumes:
      - databases-db-data:/var/lib/postgresql/data/


  neo4j:
    image: neo4j:5.16.0-community-bullseye
    ports:
      - 7474:7474
      - 7687:7687
    restart: always
    logging:
      driver: none
    command: neo4j
    volumes:
      - neo4j-data:/data
      - neo4j-conf:/conf


volumes:
  vscode-go-dev:
  databases-db-data:
  neo4j-data:
  neo4j-conf:
