version: "3.8"

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  clickhouse:
    image: 'clickhouse/clickhouse-server:24.2-alpine'
    hostname: clickhouse
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ports:
      - '127.0.0.1:8123:8123'
      - '127.0.0.1:9000:9000'

volumes:
  postgres-data:
  clickhouse-data: