name: lab1_multimedia
channels:
  - defaults
  - apple
  - conda-forge
dependencies:
  - python=3.11
  - ipython_genutils
  - notebook
  - numpy>=1.16
  - matplotlib>=3.1
  - scipy
  - pillow
  - ipykernel
  - libtiff
  - scikit-learn
  - librosa
  - pandas